# Generated by Django 5.0.1 on 2026-02-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auction_start_time_product_auction_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('scrap_metals', 'خردة ومعادن'), ('electronics', 'إلكترونيات وأجهزة'), ('furniture', 'أثاث وديكور'), ('cars', 'سيارات للبيع'), ('real_estate', 'عقارات'), ('other', 'أخرى')], max_length=20),
        ),
    ]
