# Generated by Django 5.0.1 on 2026-02-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_conversation_message_delete_aipriceanalysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auction_start_time',
        ),
    ]
