# Generated by Django 5.0.1 on 2026-02-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('scrap_metals', 'خردة ومعادن'), ('electronics', 'إلكترونيات وأجهزة'), ('furniture', 'أثاث وديكور'), ('cars', 'سيارات للبيع'), ('real_estate', 'عقارات'), ('books', 'كتب'), ('other', 'أخرى')], max_length=20),
        ),
    ]
