# Generated by Django 5.0.1 on 2026-03-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_notification_useragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detected_item',
            field=models.CharField(blank=True, default='', help_text='YOLO detected class name for agent matching', max_length=100),
        ),
    ]
