# Generated by Django 5.0.1 on 2026-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_product_detected_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='requirements_prompt',
            field=models.TextField(blank=True, default='', help_text="User's natural language requirements (e.g., 'Toshiba 10kg good condition')"),
        ),
    ]
