# Generated by Django 5.0.1 on 2026-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_useragent_requirements_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reasoning',
            field=models.TextField(blank=True, default='', help_text='AI reasoning for match or rejection'),
        ),
    ]
