# Generated by Django 5.0.1 on 2026-04-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
