# Generated by Django 5.0.1 on 2026-04-14 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_alter_userprofile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVisualEmbedding',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='visual_embedding', serialize=False, to='marketplace.product')),
                ('embedding', models.JSONField(help_text='512-dim CLIP image embedding vector as a list of floats')),
                ('image_url', models.URLField(help_text='URL of the image that was embedded', max_length=500)),
                ('model_name', models.CharField(default='openai/clip-vit-base-patch32', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Visual Embedding',
                'verbose_name_plural': 'Product Visual Embeddings',
                'db_table': 'product_visual_embeddings',
            },
        ),
    ]
