# Generated by Django 5.0.1 on 2026-04-26 21:08

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_alter_product_category'),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name='productvisualembedding',
            name='embedding',
        ),
        migrations.AddField(
            model_name='productvisualembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=512, help_text='512-dim CLIP image embedding vector', default=None, null=True),
        ),
    ]
