# Generated by Django 5.0.1 on 2026-04-26 21:27

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_alter_productvisualembedding_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvisualembedding',
            name='embedding',
        ),
        migrations.AddField(
            model_name='productvisualembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='768-dim Vision-based text embedding vector', null=True),
        ),
    ]
