# Generated by Django 5.0.1 on 2026-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_add_image_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'شحن رصيد'), ('bid_hold', 'حجز مزايدة'), ('bid_refund', 'استرداد مزايدة'), ('bid_deduct', 'خصم فوز مزايدة'), ('purchase', 'شراء مباشر'), ('sale', 'بيع مباشر')], max_length=20),
        ),
    ]
