# Generated by Django 5.0.1 on 2026-05-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, help_text="User's response to bid_approval: True=approved, False=rejected, None=pending", null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('bid_approval', 'Bid Approval')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.auction'),
        ),
        migrations.AddField(
            model_name='notification',
            name='suggested_bid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested bid amount for bid_approval notifications', max_digits=10, null=True),
        ),
    ]
