# Generated by Django 5.0.1 on 2026-07-05 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_notification_approval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPendingBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount the agent previously had locked in this auction (for delta calc)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('ai_reasoning', models.TextField(blank=True, default='')),
                ('is_counter_bid', models.BooleanField(default=False, help_text='True when this is a reaction to being outbid (outbid scenario)')),
                ('round_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bids', to='marketplace.useragent')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bids', to='marketplace.auction')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_bids', to='marketplace.notification')),
            ],
            options={
                'db_table': 'agent_pending_bids',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'status'], name='agent_pendi_agent_i_dbe771_idx'), models.Index(fields=['auction', 'status'], name='agent_pendi_auction_a61119_idx')],
            },
        ),
    ]
