# Generated by Django 5.0.1 on 2026-04-06 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0010_useragent_requirements_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='marketplace.product')),
                ('embedding', models.JSONField(help_text='1536-dim embedding vector as a list of floats')),
                ('embedded_text', models.TextField(help_text='The text that was used to generate the embedding')),
                ('model_name', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Embedding',
                'verbose_name_plural': 'Product Embeddings',
                'db_table': 'product_embeddings',
            },
        ),
        migrations.CreateModel(
            name='RAGQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('generated_sql', models.TextField(blank=True, default='')),
                ('sql_results_count', models.IntegerField(default=0)),
                ('vector_results_count', models.IntegerField(default=0)),
                ('merged_results_count', models.IntegerField(default=0)),
                ('final_answer', models.TextField(blank=True, default='')),
                ('latency_ms', models.IntegerField(default=0, help_text='Total query time in milliseconds')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG Query Log',
                'verbose_name_plural': 'RAG Query Logs',
                'db_table': 'rag_query_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
